### ISSUE TITLE
Old URLs don't redirect correctly to new website URLs

### ISSUE THREAD

**Issue by StrayEddy** [UPBGE/upbge.github.io#5]
Old urls for documentation start with: **https://upbge.org/manual/manual/...**
while the new website starts with **https://upbge.org/#/documentation/docs/latest/manual/manual/...**

Therefore clicking on links to the old documentation leads to 404 error from github

**Comment by rpaladin** [comment]
Where are you finding these older URL links? From the links displayed in the informational header in the UPBGE application?

**Comment by lordloki** [comment]
I just fixed the links in the UPBGE-Docs repository. Also, i asked for a new reindexing in google search for our site.
Additionally, I included a new 404 error redirecting to avoid 404 message error in the case any link doesn't work.
And, fixed the links inside UPBGE app help menu few second ago.

**Comment by StrayEddy** [comment]
> Where are you finding these older URL links? From the links displayed in the informational header in the UPBGE application?

I just search on Google "upbge bge logic", for example, and one of the results points to "https://upbge.org/manual/manual/logic/actuators/types/game.html". This leads, as of right now, to the home page and not the appropriate page of the doc

**Comment by lordloki** [comment]
We already asked for sitemap reindexing to Google but it is a process that takes around 4 weeks to 4 months.
Currently, GitHub hosting doesn't allow redirecting in server side, therefore we will have to wait these 4 weeks-4 months to avoid this issue.
I will close the issue when I detect that it is solve in Google search

**Comment by lordloki** [comment]
This is already fixed now. Closing the issue. Thanks for the feedback and information.
